In [1]:
import numpy as np
import pandas as pd

data_train = pd.read_csv("F:/contest/education/dataset/train.csv")
data_test = pd.read_csv("F:/contest/education/dataset/test.csv")

In [2]:
for i in range(0,10,2):
    data_test.ix[:,i][data_test.ix[:,i] == 'C'] = 1
    data_test.ix[:,i][data_test.ix[:,i] == 'D'] = 2
    data_test.ix[:,i][data_test.ix[:,i] == 'H'] = 3
    data_test.ix[:,i][data_test.ix[:,i] == 'S'] = 4

for i in range(1,10,2):
    data_test.ix[:,i][data_test.ix[:,i] == 'J'] = 11
    data_test.ix[:,i][data_test.ix[:,i] == 'Q'] = 12
    data_test.ix[:,i][data_test.ix[:,i] == 'K'] = 13 

for i in range(0,10):
    data_test.ix[:,i] = data_test.ix[:,i].astype(int)

F:\python\venv\anaconda\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

In [3]:
for i in range(0,10,2):
    data_train.ix[:,i][data_train.ix[:,i] == 'C'] = 1
    data_train.ix[:,i][data_train.ix[:,i] == 'D'] = 2
    data_train.ix[:,i][data_train.ix[:,i] == 'H'] = 3
    data_train.ix[:,i][data_train.ix[:,i] == 'S'] = 4

for i in range(1,10,2):
    data_train.ix[:,i][data_train.ix[:,i] == 'J'] = 11
    data_train.ix[:,i][data_train.ix[:,i] == 'Q'] = 12
    data_train.ix[:,i][data_train.ix[:,i] == 'K'] = 13 

for i in range(0,11):
    data_train.ix[:,i] = data_train.ix[:,i].astype(int)

F:\python\venv\anaconda\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

F:\python\venv\anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

F:\python\venv\anaconda\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
F:\python\venv\anaconda\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
F:\python\venv\anaconda\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
F:\python\venv\anaconda\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

F:\python\venv\anaconda\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
F:\python\venv\anaconda\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.

In [152]:
%%time
# data_train = data_train[['one','thr','fiv', 'sev', 'nin','two','fou','six','eig','ten','ele']]






def countcontinue1(data):
    data = list(set(sorted(data[0:5])))
    now = 0
    start = 0
    maxcon = 0
    while(start < len(data)-1):
        if(data[start+1] - data[start] == 1):
            now += 1
            
        else:
            now = 0
        maxcon = max([maxcon, now])     
        start += 1 
    return maxcon
def countcontinue2(data):
    data = list(set(sorted(data[5:11])))
    now = 0
    start = 0
    maxcon = 0
    while(start < len(data)-1):
        if(data[start+1] - data[start] == 1):
            now += 1
            
        else:
            now = 0
        maxcon = max([maxcon, now])     
        start += 1 
    return maxcon
def countsame1(data):
    return max(data[0:5].value_counts())
def countsame2(data):
    return max(data[5:10].value_counts())

def countsame2_2(data):
    return sorted(list(data[5:10].value_counts()), reverse = True)[1]
def countsame1_2(data):
    if len(list(data[0:5].value_counts())) > 1:
        return sorted(list(data[0:5].value_counts()), reverse = True)[1]
    else:
        return 0
def countgreater10(data):
    return (data>9).sum()

# data_train['continue1'] = data_train.apply(countcontinue1, axis = 1)
data_train['continue2'] = data_train.apply(countcontinue2,axis = 1)
# data_train['same1'] = data_train.apply(countsame1,axis = 1)
# data_train['same2'] = data_train.apply(countsame2,axis = 1)
# data_train['same1_2'] = data_train.apply(countsame1_2,axis =1)
# data_train['same2_2'] = data_train.apply(countsame2_2,axis =1)
# data_train['greater10'] = data_train.apply(countgreater10, axis = 1)

Wall time: 4.15 s

In [145]:
%%time
# data_test = data_test[['one','thr','fiv', 'sev', 'nin','two','fou','six','eig','ten']]






def countcontinue1(data):
    data = list(set(sorted(data[0:5])))
    now = 0
    start = 0
    maxcon = 0
    while(start < len(data)-1):
        if(data[start+1] - data[start] == 1):
            now += 1
            
        else:
            now = 0
        maxcon = max([maxcon, now])     
        start += 1 
    return maxcon
def countcontinue2(data):
    data = list(set(sorted(data[5:11])))
    now = 0
    start = 0
    maxcon = 0
    while(start < len(data)-1):
        if(data[start+1] - data[start] == 1):
            now += 1
            
        else:
            now = 0
        maxcon = max([maxcon, now])     
        start += 1 
    return maxcon
def countsame1(data):
    return max(data[0:5].value_counts())
def countsame2(data):
    return max(data[5:10].value_counts())

def countsame2_2(data):
    return sorted(list(data[5:10].value_counts()), reverse = True)[1]
def countsame1_2(data):
    if len(list(data[0:5].value_counts())) > 1:
        return sorted(list(data[0:5].value_counts()), reverse = True)[1]
    else:
        return 0

# data_test['continue1'] = data_test.apply(countcontinue1, axis = 1)
data_test['continue2'] = data_test.apply(countcontinue2,axis = 1)
# data_test['same1'] = data_test.apply(countsame1,axis = 1)
# data_test['same2'] = data_test.apply(countsame2,axis = 1)
# data_test['same1_2'] = data_test.apply(countsame1_2,axis =1)
# data_test['same2_2'] = data_test.apply(countsame2_2,axis =1)


# def countgreater10(data):
#     return (data>9).sum()
# data_test['greater10'] = data_test.apply(countgreater10, axis = 1)

Wall time: 16 s

In [181]:
%%time
import lightgbm as lgb
LGBM = lgb.LGBMClassifier(
                         max_depth=7, 
                         n_estimators=100, 
                         learning_rate=0.1, 
                         num_leaves=63, 
                         min_samples_split=2)
df = data_train.as_matrix()

X = df[:,12:]



y = list(df[:,11])
LGBM.fit(X,y)

Wall time: 1.93 s

In [182]:
res12 = LGBM.predict(data_test.as_matrix()[:,11:18])

F:\python\venv\anaconda\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

In [147]:
def to14(data):
    if data.continue2 == 3 and data.greater10 == 4 and (1 in data[5:10].values) :
        return 14
    else:
        return -1
data_train['1to14'] = data_train.apply(to14, axis = 1)

In [122]:
test_columns = list(data_test.columns)[:-1]
test_columns.insert(test_columns.index('continue1'), '1to14')
data_test = data_test[test_columns]

In [183]:
for i in range(10):
    print(i, (res12==i).sum()/100000)
    print(i,  data_train[data_train.ele == i].shape[0]/25010)

0 0.50182
0 0.4995201919232307
1 0.02116
1 0.020511795281887246
2 0.04629
2 0.04822071171531388
3 0.42321
3 0.42379048380647744
4 0.00373
4 0.003718512594962015
5 0.00211
5 0.0021591363454618153
6 0.0014
6 0.0014394242303078768
7 0.00027
7 0.0009596161535385846
8 0.0
8 0.00019992003198720512
9 1e-05
9 0.00019992003198720512

In [146]:
data_test[data_test.continue2 == 4]

,one,thr,fiv,sev,nin,two,fou,six,eig,ten,1to14,continue1,continue2,same1,same2,same1_2,same2_2,greater10,label
6,1,4,4,3,3,7,8,6,9,10,-1,1,4,2,1,2,1,1,4
424,3,3,4,3,1,4,2,3,6,5,-1,1,4,3,1,1,1,0,4
513,1,4,4,2,1,4,6,3,5,2,-1,1,4,2,1,2,1,0,4
731,4,3,4,2,1,13,12,10,11,9,-1,3,4,2,1,1,1,4,4
1149,2,1,4,1,1,3,5,2,4,1,-1,1,4,3,1,1,1,0,4
1659,1,4,4,2,3,2,5,4,3,6,-1,3,4,2,1,1,1,0,4
1801,2,3,1,1,2,11,10,8,9,12,-1,2,4,2,1,2,1,3,4
2102,3,2,3,1,1,3,6,5,7,4,-1,2,4,2,1,2,1,0,4
2333,3,1,3,3,1,4,1,3,5,2,-1,0,4,3,1,2,1,0,4
2979,1,3,3,3,1,6,4,7,3,5,-1,0,4,3,1,2,1,0,4
3083,2,2,4,2,3,4,8,6,5,7,-1,2,4,3,1,1,1,0,4
3194,4,1,2,3,2,5,4,3,6,2,-1,3,4,2,1,1,1,0,4
3306,1,4,2,1,4,11,10,9,8,7,-1,1,4,2,1,2,1,2,4
3774,1,2,3,3,4,7,8,6,9,5,-1,3,4,2,1,1,1,0,4
4001,1,1,2,4,2,4,3,6,5,2,-1,1,4,2,1,2,1,0,4
4046,4,4,4,1,1,13,11,10,12,1,14,0,4,3,1,2,1,4,0
4055,4,3,1,2,1,5,9,8,6,7,-1,3,4,2,1,1,1,0,4
4333,4,3,1,4,1,8,7,4,5,6,-1,1,4,2,1,2,1,0,4
4423,2,1,4,4,3,8,6,7,9,10,-1,3,4,2,1,1,1,1,4
4584,1,4,3,2,1,10,6,9,8,7,-1,3,4,2,1,1,1,1,4
4638,3,2,2,2,4,9,11,13,12,10,-1,2,4,3,1,1,1,4,4
4902,2,4,2,1,3,7,9,8,5,6,-1,3,4,2,1,1,1,0,4
4947,1,4,3,2,2,7,9,6,8,10,-1,3,4,2,1,1,1,1,4
5391,3,1,2,1,1,1,2,4,3,5,-1,2,4,3,1,1,1,0,4
5539,1,1,3,2,2,4,1,5,3,2,-1,2,4,2,1,2,1,0,4
5777,3,4,3,1,4,9,11,12,10,8,-1,1,4,2,1,2,1,3,4
5967,4,1,1,1,4,11,8,12,10,9,-1,0,4,3,1,2,1,3,4
6033,2,1,2,2,3,7,8,11,10,9,-1,2,4,3,1,1,1,2,4
7092,4,4,4,2,3,10,7,8,9,11,-1,2,4,3,1,1,1,2,4
7849,3,1,4,3,2,8,6,7,5,9,-1,3,4,2,1,1,1,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92215,3,4,2,2,4,7,9,5,6,8,-1,2,4,2,1,2,1,0,4
92387,4,4,2,1,3,7,8,5,4,6,-1,3,4,2,1,1,1,0,4
92493,1,4,4,2,1,6,5,3,4,7,-1,1,4,2,1,2,1,0,4
92728,2,4,1,3,3,10,9,11,12,8,-1,3,4,2,1,1,1,3,4
92765,3,2,1,2,4,6,9,7,10,8,-1,3,4,2,1,1,1,1,4
92940,3,2,3,3,3,5,8,6,7,4,-1,1,4,4,1,1,1,0,4
93106,1,3,1,2,3,10,13,11,9,12,-1,2,4,2,1,2,1,4,4
93541,3,4,4,2,1,6,5,7,4,8,-1,3,4,2,1,1,1,0,4
93757,2,4,1,1,3,2,5,3,1,4,-1,3,4,2,1,1,1,0,4
94030,4,3,2,1,3,9,7,8,10,6,-1,3,4,2,1,1,1,1,4
94392,2,1,4,3,1,6,4,5,7,8,-1,3,4,2,1,1,1,0,4
94915,2,1,2,1,4,4,1,2,3,5,-1,1,4,2,1,2,1,0,4
95142,4,1,1,1,4,8,10,9,7,6,-1,0,4,3,1,2,1,1,4
95147,3,3,2,3,3,2,3,4,5,1,-1,1,4,4,1,1,1,0,4
95251,3,3,1,2,3,5,2,3,1,4,-1,2,4,3,1,1,1,0,4
95633,4,1,4,1,1,10,11,8,9,12,-1,0,4,3,1,2,1,3,4
95977,1,3,2,3,1,5,2,6,3,4,-1,2,4,2,1,2,1,0,4
96000,3,3,3,3,4,8,4,5,6,7,-1,1,4,4,1,1,1,0,4
96172,1,2,4,4,1,8,5,6,4,7,-1,1,4,2,1,2,1,0,4
96420,3,2,4,1,2,7,10,11,9,8,-1,3,4,2,1,1,1,2,4
96438,3,4,3,1,4,11,1,10,13,12,14,1,4,2,1,2,1,4,0
96486,3,2,1,1,2,12,13,10,9,11,-1,2,4,2,1,2,1,4,4
96594,1,2,1,3,3,13,1,12,10,11,14,2,4,2,1,2,1,4,0
96650,2,2,2,3,1,9,11,8,12,10,-1,2,4,3,1,1,1,3,4
96745,3,1,2,4,3,12,1,11,10,13,14,3,4,2,1,1,1,4,0
97008,3,4,4,1,1,3,6,2,4,5,-1,1,4,2,1,2,1,0,4
98177,3,1,4,2,2,5,6,4,8,7,-1,3,4,2,1,1,1,0,4
98818,4,1,4,3,4,5,3,2,1,4,-1,1,4,3,1,1,1,0,4
98844,4,1,2,3,3,11,12,1,13,10,14,3,4,2,1,1,1,4,0
99616,2,2,4,1,4,7,5,4,3,6,-1,1,4,2,1,2,1,0,4

In [154]:
data_train[data_train.continue2 == 4]

,one,thr,fiv,sev,nin,two,fou,six,eig,ten,1to14,ele,continue1,continue2,same1,same2,same1_2,same2_2,greater10
0,3,3,3,3,3,10,11,12,13,1,14,9,0,4,5,1,0,1,4
1,4,4,4,4,4,11,13,12,10,1,14,9,0,4,5,1,0,1,4
2,2,2,2,2,2,12,11,10,13,1,14,9,0,4,5,1,0,1,4
3,1,1,1,1,1,10,11,13,1,12,14,9,0,4,5,1,0,1,4
4,1,1,1,1,1,1,13,11,12,10,14,9,0,4,5,1,0,1,4
5,3,3,3,3,3,2,4,3,5,6,-1,8,0,4,5,1,0,1,0
6,3,3,3,3,3,9,12,11,10,13,-1,8,0,4,5,1,0,1,4
7,4,4,4,4,4,1,2,4,3,5,-1,8,0,4,5,1,0,1,0
8,2,2,2,2,2,5,6,7,9,8,-1,8,0,4,5,1,0,1,0
9,1,1,1,1,1,1,4,3,2,5,-1,8,0,4,5,1,0,1,0
16,3,3,2,3,2,4,1,5,3,2,-1,4,1,4,3,1,2,1,0
402,3,2,1,2,4,11,12,9,10,13,-1,4,3,4,2,1,1,1,4
769,2,3,2,1,1,9,10,7,11,8,-1,4,2,4,2,1,2,1,2
850,4,1,4,1,3,5,2,3,4,6,-1,4,1,4,2,1,2,1,0
1020,2,3,2,2,2,10,7,11,8,9,-1,4,1,4,4,1,1,1,2
1063,2,4,3,2,4,8,7,6,9,5,-1,4,2,4,2,1,2,1,0
1279,3,2,3,4,4,2,4,1,5,3,-1,4,2,4,2,1,2,1,0
1859,2,4,4,3,2,6,7,4,5,8,-1,4,2,4,2,1,2,1,0
2024,4,4,2,4,2,8,10,9,6,7,-1,4,0,4,3,1,2,1,1
2025,2,2,2,4,4,11,12,8,9,10,-1,4,0,4,3,1,2,1,3
3085,4,1,1,3,1,13,11,10,12,9,-1,4,1,4,3,1,1,1,4
3533,3,2,4,3,4,12,10,11,8,9,-1,4,2,4,2,1,2,1,3
3562,1,4,1,2,2,5,6,9,7,8,-1,4,1,4,2,1,2,1,0
3578,2,3,1,3,4,1,3,4,5,2,-1,4,3,4,2,1,1,1,0
3591,3,2,3,1,3,1,12,10,11,13,14,4,2,4,3,1,1,1,4
3661,2,1,1,4,4,2,5,3,1,4,-1,4,1,4,2,1,2,1,0
3757,2,1,1,1,2,9,10,12,11,13,-1,4,1,4,3,1,2,1,4
4320,2,3,4,3,2,4,5,7,8,6,-1,4,2,4,2,1,2,1,0
4361,3,4,4,2,3,3,2,1,4,5,-1,4,2,4,2,1,2,1,0
4384,2,1,1,4,2,3,5,6,4,2,-1,4,1,4,2,1,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15532,2,1,2,3,3,13,10,12,1,11,14,4,2,4,2,1,2,1,4
16385,2,4,3,1,3,6,7,8,5,4,-1,4,3,4,2,1,1,1,0
16714,2,2,3,1,4,7,8,6,4,5,-1,4,3,4,2,1,1,1,0
16817,1,1,3,4,2,10,11,12,13,1,14,4,3,4,2,1,1,1,4
17279,2,4,4,2,4,10,13,1,11,12,14,4,0,4,3,1,2,1,4
17507,3,3,3,2,4,3,2,4,5,6,-1,4,2,4,3,1,1,1,0
17521,1,1,4,1,2,5,6,7,9,8,-1,4,1,4,3,1,1,1,0
18094,4,1,3,3,4,6,8,4,7,5,-1,4,1,4,2,1,2,1,0
18317,3,1,4,4,1,3,5,7,6,4,-1,4,1,4,2,1,2,1,0
18666,3,2,2,1,3,12,9,11,10,13,-1,4,2,4,2,1,2,1,4
18955,2,3,4,2,4,1,12,11,13,10,14,4,2,4,2,1,2,1,4
19255,1,2,3,3,1,3,4,1,5,2,-1,4,2,4,2,1,2,1,0
19401,1,3,1,3,1,10,13,12,9,11,-1,4,0,4,3,1,2,1,4
19643,2,4,4,4,2,6,2,4,5,3,-1,4,0,4,3,1,2,1,0
19868,3,1,1,4,1,13,1,11,12,10,14,4,1,4,3,1,1,1,4
20599,3,1,4,2,4,4,7,3,5,6,-1,4,3,4,2,1,1,1,0
20697,3,1,3,4,3,9,10,6,8,7,-1,4,1,4,3,1,1,1,1
21036,1,2,3,1,4,13,12,11,10,9,-1,4,3,4,2,1,1,1,4
21886,1,1,4,2,2,4,8,5,7,6,-1,4,1,4,2,1,2,1,0
22127,3,2,1,2,2,5,6,4,7,3,-1,4,2,4,3,1,1,1,0
22330,4,3,3,3,4,13,12,10,11,9,-1,4,1,4,3,1,2,1,4
22474,4,2,3,3,3,12,10,9,13,11,-1,4,2,4,3,1,1,1,4
22917,2,3,3,1,3,8,11,9,12,10,-1,4,2,4,3,1,1,1,3
23091,2,3,1,4,1,8,6,4,7,5,-1,4,3,4,2,1,1,1,0
23201,2,3,3,2,2,3,6,5,4,2,-1,4,1,4,3,1,2,1,0
23271,2,2,2,2,4,11,13,10,12,1,14,4,0,4,4,1,1,1,4
23618,4,4,2,4,3,6,8,7,4,5,-1,4,2,4,3,1,1,1,0
24099,4,3,4,1,1,12,13,11,9,10,-1,4,1,4,2,1,2,1,4
24224,2,2,3,3,2,13,10,11,1,12,14,4,1,4,3,1,2,1,4
24341,4,4,3,1,1,9,12,11,8,10,-1,4,1,4,2,1,2,1,3

In [184]:
# data_train[data_train.ele == 4]
# data_test[data_test.label == 4]
# data_train = pd.concat([data_train,data_train[data_train.ele == 7]]).reset_index(drop = True)
pd.DataFrame(res12).to_csv("F:/contest/education/dsjyycxds_preliminary.txt", index = False)

In [ ]:
data_train.loc[25010] = data_train.loc[8466]
data_train.loc[25011] = data_train.loc[8466]
data_train.loc[25012] = data_train.loc[8466]
data_train.loc[25013] = data_train.loc[8466]
data_train.loc[25014] = data_train.loc[8466]
data_train.loc[25015] = data_train.loc[8466]
data_train.loc[25016] = data_train.loc[8466]
data_train.loc[25016].continue2 = 1
data_train.loc[25015].continue2 = 1

In [57]:
import numpy as np
import pandas as pd

data_train = pd.read_csv("F:/contest/education/dsjyycxds_preliminary.txt")
data_test = pd.read_csv("F:/contest/education/99.9.txt")

In [58]:
count = 0
for i in range(99999):
    if data_train.iloc[i,0] != data_test.iloc[i,0]:
        count += 1
count

27

In [53]:
data_train[data_train.ele == 5].shape

(54, 18)

In [180]:
data_train

,one,thr,fiv,sev,nin,two,fou,six,eig,ten,1to14,ele,continue1,continue2,same1,same2,same1_2,same2_2,greater10
0,3,3,3,3,3,10,11,12,13,1,14,9,0,4,5,1,0,1,4
1,4,4,4,4,4,11,13,12,10,1,14,9,0,4,5,1,0,1,4
2,2,2,2,2,2,12,11,10,13,1,14,9,0,4,5,1,0,1,4
3,1,1,1,1,1,10,11,13,1,12,14,9,0,4,5,1,0,1,4
4,1,1,1,1,1,1,13,11,12,10,14,9,0,4,5,1,0,1,4
5,3,3,3,3,3,2,4,3,5,6,-1,8,0,4,5,1,0,1,0
6,3,3,3,3,3,9,12,11,10,13,-1,8,0,4,5,1,0,1,4
7,4,4,4,4,4,1,2,4,3,5,-1,8,0,4,5,1,0,1,0
8,2,2,2,2,2,5,6,7,9,8,-1,8,0,4,5,1,0,1,0
9,1,1,1,1,1,1,4,3,2,5,-1,8,0,4,5,1,0,1,0
10,3,4,3,2,4,1,1,5,9,3,-1,3,2,0,2,2,2,1,0
11,4,4,4,1,1,6,1,4,13,9,-1,0,0,0,3,1,2,1,1
12,3,1,3,3,2,10,6,1,2,8,-1,0,2,1,3,1,1,1,1
13,4,4,3,1,4,13,1,5,4,11,-1,0,1,1,3,1,1,1,2
14,2,1,1,2,2,8,12,2,9,2,-1,3,1,1,3,2,2,1,1
15,3,1,4,3,1,3,7,4,5,13,-1,0,1,2,2,1,2,1,1
16,3,3,2,3,2,4,1,5,3,2,-1,4,1,4,3,1,2,1,0
17,2,2,4,4,3,8,12,6,7,2,-1,0,2,2,2,1,2,1,1
18,1,3,2,1,1,8,11,2,6,12,-1,0,2,1,3,1,1,1,2
19,2,4,3,1,2,7,7,12,11,1,-1,3,3,1,2,2,1,1,2
20,3,1,4,4,2,13,8,10,7,13,-1,3,3,1,2,2,1,1,3
21,4,4,3,3,2,6,8,4,11,7,-1,0,2,2,2,1,2,1,1
22,2,4,3,1,2,10,10,2,5,8,-1,3,3,0,2,2,1,1,2
23,4,2,3,1,1,1,13,9,6,1,-1,3,3,0,2,2,1,1,1
24,4,4,2,3,4,10,8,2,8,13,-1,3,2,0,3,2,1,1,2
25,4,3,1,1,2,13,5,8,5,3,-1,3,3,0,2,2,1,1,1
26,2,3,2,4,3,1,5,13,7,1,-1,3,2,0,2,2,2,1,1
27,3,3,3,1,4,7,5,6,8,6,-1,3,1,3,3,2,1,1,0
28,2,2,4,4,1,7,9,5,12,4,-1,0,1,1,2,1,2,1,1
29,4,3,1,3,4,10,1,6,12,8,-1,0,1,0,2,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24998,3,1,3,1,3,8,1,13,12,10,-1,0,0,1,3,1,2,1,3
24999,1,2,2,1,4,12,11,12,4,12,-1,1,1,0,2,3,2,1,4
25000,4,4,1,1,1,8,12,2,3,4,-1,0,0,2,3,1,2,1,1
25001,4,2,1,2,1,12,5,1,8,2,-1,0,1,1,2,1,2,1,1
25002,1,4,1,1,3,10,13,7,5,5,-1,3,1,0,3,2,1,1,2
25003,3,4,1,4,3,12,9,8,12,13,-1,3,1,1,2,2,2,1,3
25004,2,2,2,1,2,5,7,11,11,2,-1,3,1,0,4,2,1,1,2
25005,2,4,1,1,4,9,6,12,11,4,-1,0,1,1,2,1,2,1,2
25006,1,1,2,2,3,1,10,4,13,10,-1,3,2,0,2,2,2,1,3
25007,4,4,1,1,1,1,10,1,4,13,-1,3,0,0,3,2,2,1,2
25008,4,1,3,3,1,12,3,12,10,9,-1,3,1,1,2,2,2,1,3
25009,3,2,1,2,2,7,11,8,3,7,-1,3,2,1,3,2,1,1,1
25010,2,1,3,3,4,8,8,12,8,8,-1,7,3,0,2,4,1,1,1
25011,4,1,3,2,1,8,8,8,8,13,-1,7,3,0,2,4,1,1,1
25012,1,4,3,2,4,11,11,11,11,5,-1,7,3,0,2,4,1,1,4
25013,2,4,3,1,1,3,3,3,3,13,-1,7,3,0,2,4,1,1,1
25014,2,2,3,4,1,8,7,7,7,7,-1,7,3,0,2,4,1,1,0
25015,1,4,2,3,1,2,2,2,2,10,-1,7,3,0,2,4,1,1,1
25016,2,1,3,3,4,8,8,12,8,8,-1,7,3,0,2,4,1,1,1
25017,4,1,3,2,1,8,8,8,8,13,-1,7,3,0,2,4,1,1,1
25018,1,4,3,2,4,11,11,11,11,5,-1,7,3,0,2,4,1,1,4
25019,2,4,3,1,1,3,3,3,3,13,-1,7,3,0,2,4,1,1,1
25020,2,2,3,4,1,8,7,7,7,7,-1,7,3,0,2,4,1,1,0
25021,1,4,2,3,1,2,2,2,2,10,-1,7,3,0,2,4,1,1,1
25022,2,1,3,3,4,8,8,12,8,8,-1,7,3,0,2,4,1,1,1
25023,4,1,3,2,1,8,8,8,8,13,-1,7,3,0,2,4,1,1,1
25024,1,4,3,2,4,11,11,11,11,5,-1,7,3,0,2,4,1,1,4
25025,2,4,3,1,1,3,3,3,3,13,-1,7,3,0,2,4,1,1,1
25026,2,2,3,4,1,8,7,7,7,7,-1,7,3,0,2,4,1,1,0
25027,1,4,2,3,1,2,2,2,2,10,-1,7,3,0,2,4,1,1,1

In [98]:
for i in range(10):
    print(i, (res==i).sum()/100000)
    print(i,  data_train[data_train.ele == i].shape[0]/25010)

0 0.5022
0 0.4995201919232307
1 0.02116
1 0.020511795281887246
2 0.04629
2 0.04822071171531388
3 0.42321
3 0.42379048380647744
4 0.00335
4 0.003718512594962015
5 0.002
5 0.0021591363454618153
6 0.0014
6 0.0014394242303078768
7 0.00027
7 0.0009596161535385846
8 1e-05
8 0.00019992003198720512
9 0.00011
9 0.00019992003198720512

In [32]:
for i in range(10):
    print(i, (res1==i).sum()/100000)
    print(i,  data_train[data_train.ele == i].shape[0]/25010)

0 0.5022
0 0.4995201919232307
1 0.02143
1 0.020511795281887246
2 0.04629
2 0.04822071171531388
3 0.42321
3 0.42379048380647744
4 0.00333
4 0.003718512594962015
5 0.0021
5 0.0021591363454618153
6 0.0014
6 0.0014394242303078768
7 0.0
7 0.00023990403838464614
8 3e-05
8 0.00019992003198720512
9 1e-05
9 0.00019992003198720512

9,8,6,5,1

In [190]:
cmp1 = pd.read_csv("F:/contest/education/99.959.txt")

In [194]:
count = 0
for i in range(100000):
    if cmp1[i] != res12[i]:
        count += 1
count

42